const markets = window.ROOFIQ_MARKETS;
const $ = id => document.getElementById(id);
let selected = markets[0];
function scoreColor(v){ if(v>=75)return '#22c55e'; if(v>=65)return '#a3e635'; if(v>=55)return '#facc15'; if(v>=45)return '#fb923c'; return '#ef4444'; }
function project(lon,lat){ const x=(lon+125)/(58)*100; const y=(50-lat)/(26)*100; return [Math.max(2,Math.min(98,x)),Math.max(4,Math.min(96,y))]; }
function filtered(){ const q=$('search').value.toLowerCase(); const r=$('region').value; const t=$('tier').value; return markets.filter(m=>(r==='all'||m.region===r)&&(t==='all'||m.tier===t)&&(m.city.toLowerCase().includes(q)||m.state.toLowerCase().includes(q))); }
function renderSummary(list){ const avg=Math.round(list.reduce((a,m)=>a+m.roofing,0)/(list.length||1)); const top=[...list].sort((a,b)=>b.roofing-a.roofing)[0]||markets[0]; $('topMarket').textContent=`${top.city}, ${top.state}`; $('topScore').textContent=top.roofing; $('totalMarkets').textContent=list.length; $('avgScore').textContent=avg; $('highCount').textContent=list.filter(m=>m.roofing>=70).length; }
function renderMap(list){ const metric=$('metric').value; let dots=list.map(m=>{const [x,y]=project(m.lon,m.lat); const size=5+(m[metric]-45)/8; return `<circle class="dot" data-city="${m.city}" cx="${x}" cy="${y}" r="${Math.max(4,Math.min(10,size))}" fill="${scoreColor(m[metric])}" stroke="#082747" stroke-width="1.5"><title>${m.city}, ${m.state}: ${m[metric]}</title></circle>`}).join('');
 $('map').innerHTML=`<svg viewBox="0 0 100 100" width="100%" height="100%" preserveAspectRatio="none"><defs><linearGradient id="usGrad" x1="0" x2="1"><stop offset="0" stop-color="#ff8a3d"/><stop offset=".55" stop-color="#facc15"/><stop offset="1" stop-color="#22c55e"/></linearGradient></defs><path class="stateBlob" d="M7,43 C15,33 26,31 37,34 C48,35 61,34 72,38 C82,34 91,39 94,49 C91,60 82,67 70,68 C58,75 45,72 33,70 C22,68 12,62 7,51 Z"/><path class="stateBlob" d="M12,74 C17,76 20,82 18,88 C12,88 8,84 7,79 Z"/><path class="stateBlob" d="M31,83 C34,82 36,84 36,87 C33,89 30,88 29,85 Z"/>${dots}</svg>`; document.querySelectorAll('.dot').forEach(d=>d.onclick=()=>{selected=markets.find(m=>m.city===d.dataset.city); renderProfile();}); }
function renderTop(list){ $('topList').innerHTML=[...list].sort((a,b)=>b.roofing-a.roofing).slice(0,5).map((m,i)=>`<div class="topItem"><span>${i+1}. ${m.city}, ${m.state}</span><span class="badge">${m.roofing}</span></div>`).join(''); }
function renderProfile(){ $('selectedTitle').textContent=`${selected.city}, ${selected.state}`; const boxes=[['Roofing Score',selected.roofing],['FM Score',selected.fm],['Growth Score',selected.growth],['Competition',selected.competition],['Annual Rainfall',selected.rain+' in'],['Workable Days',selected.workable]]; $('profile').innerHTML=boxes.map(([k,v])=>`<div class="metricBox"><span>${k}</span><b>${v}</b></div>`).join(''); $('weatherBars').innerHTML=[['Weather Score',selected.weather],['Rain Days',Math.round(selected.rainDays/1.8)],['Workable Days',Math.round(selected.workable/3.65)],['Rainfall Load',Math.min(100,selected.rain*1.4)]].map(([k,v])=>`<div class="barRow"><span><b>${k}</b><b>${v}</b></span><div class="bar"><i style="width:${v}%"></i></div></div>`).join(''); }
function renderTable(list){ $('table').innerHTML=list.map(m=>`<tr><td><b>${m.city}, ${m.state}</b></td><td>${m.region}</td><td>${m.tier}</td><td>${m.roofing}</td><td>${m.fm}</td><td>${m.rainDays}</td><td>${m.workable}</td></tr>`).join(''); }
function render(){ const list=filtered(); if(!list.includes(selected)) selected=list[0]||markets[0]; renderSummary(list); renderMap(list); renderTop(list); renderProfile(); renderTable(list); }
function init(){ [...new Set(markets.map(m=>m.region))].sort().forEach(r=>$('region').innerHTML+=`<option>${r}</option>`); ['search','region','tier','metric'].forEach(id=>$(id).addEventListener('input',render)); selected=markets.find(m=>m.city==='Nashville')||markets[0]; render(); }
init();
