export type MarketCity = {
  city: string;
  state: string;
  region: string;
  tier: 'Tier 1' | 'Tier 2' | 'Tier 3';
  population: number;
  commercialDemand: number;
  industrialGrowth: number;
  fmFit: number;
  weatherRisk: number;
  competitionPressure: number;
  laborAvailability: number;
  permitActivity: number;
  annualRainfallInches: number;
  rainDaysPerYear: number;
  workableRoofDays: number;
  notes: string;
};

export const marketData: MarketCity[] = [
  { city: 'Atlanta', state: 'GA', region: 'Southeast', tier: 'Tier 1', population: 6307000, commercialDemand: 88, industrialGrowth: 86, fmFit: 82, weatherRisk: 74, competitionPressure: 68, laborAvailability: 72, permitActivity: 84, annualRainfallInches: 50, rainDaysPerYear: 113, workableRoofDays: 235, notes: 'Large logistics base, strong commercial retrofit demand, weather delays manageable but real.' },
  { city: 'Dallas-Fort Worth', state: 'TX', region: 'Texas', tier: 'Tier 1', population: 8100000, commercialDemand: 94, industrialGrowth: 90, fmFit: 86, weatherRisk: 82, competitionPressure: 78, laborAvailability: 70, permitActivity: 88, annualRainfallInches: 39, rainDaysPerYear: 80, workableRoofDays: 255, notes: 'Massive industrial inventory, storm exposure, and FM-heavy distribution assets. Pricing discipline required.' },
  { city: 'Houston', state: 'TX', region: 'Texas', tier: 'Tier 1', population: 7500000, commercialDemand: 93, industrialGrowth: 88, fmFit: 84, weatherRisk: 88, competitionPressure: 75, laborAvailability: 68, permitActivity: 86, annualRainfallInches: 53, rainDaysPerYear: 104, workableRoofDays: 230, notes: 'Huge commercial roof base with hurricane, rain, humidity, and industrial plant exposure. High upside, high chaos.' },
  { city: 'Austin', state: 'TX', region: 'Texas', tier: 'Tier 1', population: 2500000, commercialDemand: 85, industrialGrowth: 84, fmFit: 74, weatherRisk: 78, competitionPressure: 70, laborAvailability: 66, permitActivity: 85, annualRainfallInches: 35, rainDaysPerYear: 79, workableRoofDays: 255, notes: 'Growth market with tech, mixed commercial, and strong construction activity. Competition is not sleeping.' },
  { city: 'San Antonio', state: 'TX', region: 'Texas', tier: 'Tier 2', population: 2700000, commercialDemand: 78, industrialGrowth: 76, fmFit: 68, weatherRisk: 72, competitionPressure: 58, laborAvailability: 69, permitActivity: 75, annualRainfallInches: 32, rainDaysPerYear: 74, workableRoofDays: 260, notes: 'Steady commercial demand, lower competition than larger Texas metros, and decent workable-day profile.' },
  { city: 'Phoenix', state: 'AZ', region: 'Southwest', tier: 'Tier 1', population: 5059000, commercialDemand: 89, industrialGrowth: 88, fmFit: 74, weatherRisk: 60, competitionPressure: 70, laborAvailability: 68, permitActivity: 86, annualRainfallInches: 8, rainDaysPerYear: 36, workableRoofDays: 280, notes: 'Excellent workable-day profile and growth. Heat risk replaces rain risk because nature enjoys variety.' },
  { city: 'Las Vegas', state: 'NV', region: 'Southwest', tier: 'Tier 2', population: 2350000, commercialDemand: 76, industrialGrowth: 78, fmFit: 65, weatherRisk: 58, competitionPressure: 56, laborAvailability: 62, permitActivity: 73, annualRainfallInches: 4, rainDaysPerYear: 29, workableRoofDays: 285, notes: 'Low rain delay, fast service cycles, and hotel/commercial exposure. Heat and price sensitivity are the watchpoints.' },
  { city: 'Los Angeles', state: 'CA', region: 'West', tier: 'Tier 1', population: 12700000, commercialDemand: 94, industrialGrowth: 74, fmFit: 82, weatherRisk: 61, competitionPressure: 88, laborAvailability: 58, permitActivity: 72, annualRainfallInches: 15, rainDaysPerYear: 36, workableRoofDays: 275, notes: 'Enormous roof inventory but brutal competition, labor cost, access issues, and regulatory drag.' },
  { city: 'Inland Empire', state: 'CA', region: 'West', tier: 'Tier 1', population: 4700000, commercialDemand: 89, industrialGrowth: 92, fmFit: 82, weatherRisk: 64, competitionPressure: 76, laborAvailability: 60, permitActivity: 80, annualRainfallInches: 13, rainDaysPerYear: 35, workableRoofDays: 275, notes: 'Warehouse-heavy market with strong FM and logistics fit. Labor and access planning matter.' },
  { city: 'San Diego', state: 'CA', region: 'West', tier: 'Tier 2', population: 3300000, commercialDemand: 76, industrialGrowth: 66, fmFit: 70, weatherRisk: 55, competitionPressure: 72, laborAvailability: 57, permitActivity: 68, annualRainfallInches: 10, rainDaysPerYear: 38, workableRoofDays: 278, notes: 'Good commercial base, low rain disruption, higher labor and operating costs.' },
  { city: 'San Francisco Bay Area', state: 'CA', region: 'West', tier: 'Tier 1', population: 7700000, commercialDemand: 88, industrialGrowth: 76, fmFit: 84, weatherRisk: 66, competitionPressure: 84, laborAvailability: 55, permitActivity: 70, annualRainfallInches: 23, rainDaysPerYear: 68, workableRoofDays: 245, notes: 'High-value commercial/institutional roofs with heavy labor, access, and cost constraints.' },
  { city: 'Seattle', state: 'WA', region: 'West', tier: 'Tier 2', population: 4018000, commercialDemand: 78, industrialGrowth: 75, fmFit: 76, weatherRisk: 80, competitionPressure: 69, laborAvailability: 66, permitActivity: 73, annualRainfallInches: 39, rainDaysPerYear: 156, workableRoofDays: 190, notes: 'Rain-day drag is severe. Good market, but production planning needs adult supervision.' },
  { city: 'Portland', state: 'OR', region: 'West', tier: 'Tier 2', population: 2500000, commercialDemand: 73, industrialGrowth: 72, fmFit: 70, weatherRisk: 78, competitionPressure: 60, laborAvailability: 65, permitActivity: 68, annualRainfallInches: 36, rainDaysPerYear: 154, workableRoofDays: 192, notes: 'Wet climate and steady industrial base. Production planning and leak-service positioning matter.' },
  { city: 'Denver', state: 'CO', region: 'Mountain', tier: 'Tier 1', population: 3005000, commercialDemand: 86, industrialGrowth: 79, fmFit: 77, weatherRisk: 82, competitionPressure: 72, laborAvailability: 63, permitActivity: 78, annualRainfallInches: 15, rainDaysPerYear: 83, workableRoofDays: 250, notes: 'High hail exposure and strong retrofit market. Labor and competition are the friction points.' },
  { city: 'Salt Lake City', state: 'UT', region: 'Mountain', tier: 'Tier 2', population: 1260000, commercialDemand: 74, industrialGrowth: 82, fmFit: 70, weatherRisk: 66, competitionPressure: 55, laborAvailability: 64, permitActivity: 76, annualRainfallInches: 20, rainDaysPerYear: 91, workableRoofDays: 240, notes: 'Industrial expansion and manageable weather make this attractive, with less noise than larger metros.' },
  { city: 'Boise', state: 'ID', region: 'Mountain', tier: 'Tier 3', population: 850000, commercialDemand: 64, industrialGrowth: 70, fmFit: 58, weatherRisk: 61, competitionPressure: 42, laborAvailability: 58, permitActivity: 66, annualRainfallInches: 12, rainDaysPerYear: 87, workableRoofDays: 248, notes: 'Growth market with lower complexity. Smaller roof universe but good expansion candidate.' },
  { city: 'Albuquerque', state: 'NM', region: 'Southwest', tier: 'Tier 3', population: 925000, commercialDemand: 61, industrialGrowth: 58, fmFit: 55, weatherRisk: 60, competitionPressure: 40, laborAvailability: 57, permitActivity: 56, annualRainfallInches: 9, rainDaysPerYear: 58, workableRoofDays: 270, notes: 'Manageable weather and lower competition, but limited premium commercial depth.' },
  { city: 'Chicago', state: 'IL', region: 'Midwest', tier: 'Tier 1', population: 9460000, commercialDemand: 92, industrialGrowth: 76, fmFit: 88, weatherRisk: 68, competitionPressure: 82, laborAvailability: 70, permitActivity: 77, annualRainfallInches: 38, rainDaysPerYear: 124, workableRoofDays: 215, notes: 'Massive roof inventory and FM-heavy institutional/commercial base. Competition and seasonality punish sloppy entrants.' },
  { city: 'Minneapolis-St. Paul', state: 'MN', region: 'Midwest', tier: 'Tier 2', population: 3700000, commercialDemand: 80, industrialGrowth: 72, fmFit: 76, weatherRisk: 76, competitionPressure: 64, laborAvailability: 68, permitActivity: 70, annualRainfallInches: 32, rainDaysPerYear: 117, workableRoofDays: 200, notes: 'Strong commercial base with real seasonality, hail exposure, and winter shutdown risk.' },
  { city: 'Detroit', state: 'MI', region: 'Midwest', tier: 'Tier 2', population: 4350000, commercialDemand: 79, industrialGrowth: 71, fmFit: 78, weatherRisk: 70, competitionPressure: 58, laborAvailability: 67, permitActivity: 66, annualRainfallInches: 34, rainDaysPerYear: 135, workableRoofDays: 200, notes: 'Large legacy industrial roof inventory with moderate growth. Retrofit and service opportunities are strong.' },
  { city: 'Indianapolis', state: 'IN', region: 'Midwest', tier: 'Tier 2', population: 2150000, commercialDemand: 78, industrialGrowth: 82, fmFit: 72, weatherRisk: 70, competitionPressure: 54, laborAvailability: 69, permitActivity: 74, annualRainfallInches: 43, rainDaysPerYear: 125, workableRoofDays: 218, notes: 'Distribution-heavy metro with practical sales motion and manageable competition.' },
  { city: 'Columbus', state: 'OH', region: 'Midwest', tier: 'Tier 2', population: 2200000, commercialDemand: 78, industrialGrowth: 80, fmFit: 72, weatherRisk: 68, competitionPressure: 58, laborAvailability: 68, permitActivity: 76, annualRainfallInches: 40, rainDaysPerYear: 130, workableRoofDays: 215, notes: 'Growth, logistics, and institutional demand make this a strong second-wave market.' },
  { city: 'Cincinnati', state: 'OH', region: 'Midwest', tier: 'Tier 3', population: 2250000, commercialDemand: 72, industrialGrowth: 70, fmFit: 68, weatherRisk: 69, competitionPressure: 52, laborAvailability: 66, permitActivity: 65, annualRainfallInches: 44, rainDaysPerYear: 132, workableRoofDays: 210, notes: 'Solid commercial base with less hype. Good for disciplined service and retrofit plays.' },
  { city: 'Cleveland', state: 'OH', region: 'Midwest', tier: 'Tier 3', population: 2050000, commercialDemand: 70, industrialGrowth: 62, fmFit: 72, weatherRisk: 72, competitionPressure: 50, laborAvailability: 65, permitActivity: 58, annualRainfallInches: 39, rainDaysPerYear: 154, workableRoofDays: 190, notes: 'Older industrial roof stock and harsh weather create service demand, but growth is muted.' },
  { city: 'St. Louis', state: 'MO', region: 'Midwest', tier: 'Tier 2', population: 2800000, commercialDemand: 76, industrialGrowth: 72, fmFit: 70, weatherRisk: 76, competitionPressure: 56, laborAvailability: 67, permitActivity: 68, annualRainfallInches: 42, rainDaysPerYear: 110, workableRoofDays: 225, notes: 'Good central distribution position with storm exposure and moderate competition.' },
  { city: 'Kansas City', state: 'MO', region: 'Midwest', tier: 'Tier 2', population: 2250000, commercialDemand: 76, industrialGrowth: 78, fmFit: 70, weatherRisk: 78, competitionPressure: 54, laborAvailability: 68, permitActivity: 72, annualRainfallInches: 39, rainDaysPerYear: 96, workableRoofDays: 238, notes: 'Logistics growth, hail/wind exposure, and lower noise than top-tier metros.' },
  { city: 'Nashville', state: 'TN', region: 'Southeast', tier: 'Tier 1', population: 2100000, commercialDemand: 82, industrialGrowth: 81, fmFit: 73, weatherRisk: 71, competitionPressure: 58, laborAvailability: 65, permitActivity: 80, annualRainfallInches: 49, rainDaysPerYear: 119, workableRoofDays: 230, notes: 'Fast growth and retrofit opportunity, but weather interruptions and labor pressure need pricing discipline.' },
  { city: 'Charlotte', state: 'NC', region: 'Southeast', tier: 'Tier 1', population: 2805000, commercialDemand: 84, industrialGrowth: 83, fmFit: 78, weatherRisk: 70, competitionPressure: 61, laborAvailability: 69, permitActivity: 82, annualRainfallInches: 43, rainDaysPerYear: 105, workableRoofDays: 245, notes: 'Strong growth, banking/corporate campuses, distribution expansion, moderate competitive pressure.' },
  { city: 'Raleigh-Durham', state: 'NC', region: 'Southeast', tier: 'Tier 2', population: 2300000, commercialDemand: 78, industrialGrowth: 77, fmFit: 72, weatherRisk: 68, competitionPressure: 54, laborAvailability: 68, permitActivity: 78, annualRainfallInches: 46, rainDaysPerYear: 108, workableRoofDays: 242, notes: 'Institutional, tech, healthcare, and life-science demand with manageable market size.' },
  { city: 'Greenville-Spartanburg', state: 'SC', region: 'Southeast', tier: 'Tier 3', population: 1200000, commercialDemand: 70, industrialGrowth: 80, fmFit: 68, weatherRisk: 69, competitionPressure: 42, laborAvailability: 63, permitActivity: 70, annualRainfallInches: 50, rainDaysPerYear: 111, workableRoofDays: 235, notes: 'Manufacturing and logistics corridor with lower competition and attractive target density.' },
  { city: 'Charleston', state: 'SC', region: 'Southeast', tier: 'Tier 3', population: 850000, commercialDemand: 68, industrialGrowth: 74, fmFit: 64, weatherRisk: 82, competitionPressure: 48, laborAvailability: 58, permitActivity: 70, annualRainfallInches: 51, rainDaysPerYear: 106, workableRoofDays: 225, notes: 'Port, logistics, and storm exposure. Smaller market with real weather risk.' },
  { city: 'Jacksonville', state: 'FL', region: 'Southeast', tier: 'Tier 2', population: 1750000, commercialDemand: 78, industrialGrowth: 79, fmFit: 70, weatherRisk: 84, competitionPressure: 58, laborAvailability: 62, permitActivity: 75, annualRainfallInches: 52, rainDaysPerYear: 113, workableRoofDays: 225, notes: 'Port logistics, storm exposure, and strong year-round activity. Moisture risk is not decorative.' },
  { city: 'Orlando', state: 'FL', region: 'Southeast', tier: 'Tier 1', population: 2700000, commercialDemand: 84, industrialGrowth: 78, fmFit: 72, weatherRisk: 86, competitionPressure: 68, laborAvailability: 63, permitActivity: 82, annualRainfallInches: 53, rainDaysPerYear: 118, workableRoofDays: 220, notes: 'Hospitality, distribution, healthcare, and storm exposure. High demand with high contractor density.' },
  { city: 'Tampa-St. Petersburg', state: 'FL', region: 'Southeast', tier: 'Tier 1', population: 3350000, commercialDemand: 85, industrialGrowth: 76, fmFit: 74, weatherRisk: 88, competitionPressure: 70, laborAvailability: 62, permitActivity: 80, annualRainfallInches: 51, rainDaysPerYear: 105, workableRoofDays: 225, notes: 'Dense commercial base with hurricane exposure, service demand, and heavy competition.' },
  { city: 'Miami-Fort Lauderdale', state: 'FL', region: 'Southeast', tier: 'Tier 1', population: 6200000, commercialDemand: 90, industrialGrowth: 70, fmFit: 80, weatherRisk: 92, competitionPressure: 84, laborAvailability: 57, permitActivity: 76, annualRainfallInches: 62, rainDaysPerYear: 135, workableRoofDays: 195, notes: 'High-value roofs, code complexity, hurricane exposure, labor cost, and intense competition.' },
  { city: 'Savannah', state: 'GA', region: 'Southeast', tier: 'Tier 3', population: 420000, commercialDemand: 66, industrialGrowth: 82, fmFit: 66, weatherRisk: 78, competitionPressure: 38, laborAvailability: 57, permitActivity: 68, annualRainfallInches: 49, rainDaysPerYear: 109, workableRoofDays: 230, notes: 'Port and warehouse growth make it interesting despite smaller population.' },
  { city: 'Memphis', state: 'TN', region: 'Southeast', tier: 'Tier 2', population: 1350000, commercialDemand: 74, industrialGrowth: 82, fmFit: 70, weatherRisk: 76, competitionPressure: 48, laborAvailability: 62, permitActivity: 68, annualRainfallInches: 54, rainDaysPerYear: 108, workableRoofDays: 225, notes: 'Logistics-heavy market with storm exposure and service/retrofit potential.' },
  { city: 'New Orleans', state: 'LA', region: 'Southeast', tier: 'Tier 3', population: 1270000, commercialDemand: 72, industrialGrowth: 64, fmFit: 68, weatherRisk: 94, competitionPressure: 52, laborAvailability: 55, permitActivity: 58, annualRainfallInches: 63, rainDaysPerYear: 115, workableRoofDays: 200, notes: 'Extreme weather and moisture risk drive demand, but execution risk is high.' },
  { city: 'Washington DC-Baltimore', state: 'DC', region: 'Mid-Atlantic', tier: 'Tier 1', population: 9850000, commercialDemand: 92, industrialGrowth: 76, fmFit: 88, weatherRisk: 70, competitionPressure: 80, laborAvailability: 68, permitActivity: 78, annualRainfallInches: 42, rainDaysPerYear: 115, workableRoofDays: 220, notes: 'Federal, institutional, healthcare, and logistics inventory. High-value but procurement-heavy.' },
  { city: 'Philadelphia', state: 'PA', region: 'Northeast', tier: 'Tier 1', population: 6250000, commercialDemand: 86, industrialGrowth: 72, fmFit: 84, weatherRisk: 68, competitionPressure: 72, laborAvailability: 66, permitActivity: 70, annualRainfallInches: 44, rainDaysPerYear: 120, workableRoofDays: 210, notes: 'Large commercial inventory, institutional base, and dense competition. Service discipline wins.' },
  { city: 'New York-Newark', state: 'NY', region: 'Northeast', tier: 'Tier 1', population: 19800000, commercialDemand: 96, industrialGrowth: 70, fmFit: 90, weatherRisk: 72, competitionPressure: 94, laborAvailability: 54, permitActivity: 72, annualRainfallInches: 47, rainDaysPerYear: 121, workableRoofDays: 200, notes: 'Enormous roof universe, very high costs, access constraints, union/labor complexity, and premium accounts.' },
  { city: 'Boston', state: 'MA', region: 'Northeast', tier: 'Tier 1', population: 4900000, commercialDemand: 85, industrialGrowth: 68, fmFit: 86, weatherRisk: 70, competitionPressure: 78, laborAvailability: 56, permitActivity: 68, annualRainfallInches: 44, rainDaysPerYear: 130, workableRoofDays: 198, notes: 'High-value institutional/life-science market with seasonality and expensive execution.' },
  { city: 'Pittsburgh', state: 'PA', region: 'Northeast', tier: 'Tier 3', population: 2370000, commercialDemand: 70, industrialGrowth: 62, fmFit: 72, weatherRisk: 72, competitionPressure: 48, laborAvailability: 64, permitActivity: 58, annualRainfallInches: 39, rainDaysPerYear: 151, workableRoofDays: 190, notes: 'Older industrial and institutional roof stock with slower growth but consistent service demand.' },
  { city: 'Richmond', state: 'VA', region: 'Mid-Atlantic', tier: 'Tier 3', population: 1350000, commercialDemand: 70, industrialGrowth: 72, fmFit: 68, weatherRisk: 70, competitionPressure: 44, laborAvailability: 64, permitActivity: 68, annualRainfallInches: 44, rainDaysPerYear: 110, workableRoofDays: 230, notes: 'Solid logistics and government-adjacent demand with lower competition than DC.' },
  { city: 'Virginia Beach-Norfolk', state: 'VA', region: 'Mid-Atlantic', tier: 'Tier 3', population: 1800000, commercialDemand: 72, industrialGrowth: 70, fmFit: 68, weatherRisk: 82, competitionPressure: 48, laborAvailability: 60, permitActivity: 64, annualRainfallInches: 47, rainDaysPerYear: 116, workableRoofDays: 220, notes: 'Military, port, and coastal weather exposure. Strong niche if access/procurement is handled.' },
  { city: 'Louisville', state: 'KY', region: 'Midwest', tier: 'Tier 3', population: 1400000, commercialDemand: 70, industrialGrowth: 74, fmFit: 66, weatherRisk: 72, competitionPressure: 44, laborAvailability: 65, permitActivity: 66, annualRainfallInches: 46, rainDaysPerYear: 120, workableRoofDays: 220, notes: 'Distribution and manufacturing base with practical competition profile.' },
  { city: 'Oklahoma City', state: 'OK', region: 'Plains', tier: 'Tier 2', population: 1500000, commercialDemand: 72, industrialGrowth: 76, fmFit: 64, weatherRisk: 88, competitionPressure: 48, laborAvailability: 65, permitActivity: 70, annualRainfallInches: 36, rainDaysPerYear: 84, workableRoofDays: 250, notes: 'Severe hail/wind exposure with growing commercial base. Weather drives demand and claim cycles.' },
  { city: 'Tulsa', state: 'OK', region: 'Plains', tier: 'Tier 3', population: 1030000, commercialDemand: 66, industrialGrowth: 70, fmFit: 62, weatherRisk: 86, competitionPressure: 42, laborAvailability: 64, permitActivity: 62, annualRainfallInches: 42, rainDaysPerYear: 88, workableRoofDays: 245, notes: 'Storm exposure and industrial base create service demand in a smaller market.' },
  { city: 'Omaha', state: 'NE', region: 'Plains', tier: 'Tier 3', population: 1000000, commercialDemand: 66, industrialGrowth: 68, fmFit: 62, weatherRisk: 76, competitionPressure: 40, laborAvailability: 64, permitActivity: 62, annualRainfallInches: 31, rainDaysPerYear: 94, workableRoofDays: 235, notes: 'Stable commercial market with hail exposure and manageable competition.' },
  { city: 'Des Moines', state: 'IA', region: 'Plains', tier: 'Tier 3', population: 750000, commercialDemand: 62, industrialGrowth: 66, fmFit: 60, weatherRisk: 74, competitionPressure: 36, laborAvailability: 62, permitActivity: 60, annualRainfallInches: 36, rainDaysPerYear: 107, workableRoofDays: 225, notes: 'Smaller but workable market with insurance, industrial, and storm-driven retrofit opportunities.' }
];

export function calculateScores(city: MarketCity) {
  const roofingScore = Math.round(
    city.commercialDemand * 0.25 +
    city.industrialGrowth * 0.2 +
    city.weatherRisk * 0.15 +
    (100 - city.competitionPressure) * 0.1 +
    city.laborAvailability * 0.1 +
    city.permitActivity * 0.2
  );

  const fmScore = Math.round(
    city.fmFit * 0.4 +
    city.commercialDemand * 0.2 +
    city.industrialGrowth * 0.2 +
    city.weatherRisk * 0.1 +
    city.permitActivity * 0.1
  );

  const rainPerCapita = Number(((city.annualRainfallInches / city.population) * 1000000).toFixed(2));
  const weatherDelayRisk = Math.min(100, Math.round((city.rainDaysPerYear / 180) * 100));

  return { roofingScore, fmScore, rainPerCapita, weatherDelayRisk };
}
